### ISSUE TITLE
Error: "Skipping Url! - Cannot retrieve download information"

### ISSUE THREAD

**Issue by AveryTheBrash** [devvratmiglani/Vimmdl#1] opened 2024-07-25 17:03 UTC
Whenever I try to use vm-cli to download something, it pops up an error:

User@Device:~$ vm download https://vimm.net/vault/29850

Skipping Url! - Cannot retrieve download information.
aria2c requirement is satisfied
Traceback (most recent call last):
  File "/home/user/.local/bin/vm", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/vm/__init__.py", line 37, in _download
    downloader.start_download(dl_urls)
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/vm/downloader.py", line 54, in start_download
    aria_download(dl_urls)
  File "/home/user/.local/pipx/venvs/vm-cli/lib/python3.10/site-packages/vm/downloader.py", line 14, in aria_download
    subprocess.run(arg)
UnboundLocalError: local variable 'arg' referenced before assignment

I am on Linux Mint 21.3 Virginia. I regularly: "sudo apt update && sudo apt upgrade."
I have pipx preinstalled.
I: "sudo apt install aria2"
"pipx ensurepath"
"pipx completions"
"bash:
    eval "$(register-python-argcomplete pipx)"
"
Then I can use: "vm"
"vm consoles"
"vm search (CONSOLE) (GAME)"
All works great.

I can share more PC specs and cmd history. I should note that I tried manually changing my pathvariable a few times before I settled on the ensurepath method.

**Comment by devvratmiglani** [comment] 2024-07-25 18:38
Thanks for pointing that out. The issue is fixed now!

I have observed that nintend0 has shown its existence and hence downloads to some consoles will not be available [ can't do any thing : ( ].
 
 I have made another downloader that may work, currently unreleased and may release soon. 
 Now it works perfectly, but you may face limited downloading options with nintend0.

**Closed as completed by devvratmiglani** 2024-07-25 18:38 UTC
